name: deploy

on: [push, pull_request]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: npmRunDeploy
        working-directory: ./website
        run: |
          npm run build
          react-scripts build
          gh-pages -d build
