name: LaTeX compiler
on: push
jobs:
    compile:
        name: Compile LaTeX
        runs-on: ubuntu-20.04
        steps:
            - name: Checkout Code
              uses: actions/checkout@v2

            - name: Run XeLaTeX
              uses: xu-cheng/texlive-action/full@v1
              with:
                  run: |
                      apk add make
                      make

            - name: Deploy to GitHub Pages
              if: success()
              uses: crazy-max/ghaction-github-pages@v2
              with:
                  target_branch: gh-pages
                  build_dir: site
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

