name: Build project

on: [push, pull_request]

defaults:
  run:
    shell: bash
    working-directory: ./

jobs:
  build:
    name: Build React project
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

